eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/

database: mysql

spring:
  datasource:
    sql-script-encoding: UTF-8
    url: "jdbc:mysql://127.0.01:3306/bookstore?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
    username: "root"
    password: "root"
  resources:
    chain:
      compressed: true
      cache: true
    cache:
      period: 86400

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 输出执行的 SQL 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    # 开启驼峰命名自动映射
    map-underscore-to-camel-case: true

security:
  oauth2:
    client:
      # OAuth的ClientID和ClientSecret是写在OAuthClientDetailsService中的
      clientId: account
      clientSecret: account_secret
      accessTokenUri: http://${AUTH_HOST:localhost}:${AUTH_PORT:8301}/oauth/token
      grant-type: client_credentials
      scope: SERVICE
    resource:
      userInfoUri: BUGFIX


logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%t]){faint} %clr(%-40logger{39}){cyan}[%line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO

server:
  port: ${PORT:8401}
